# Generated by Django 3.2.21 on 2023-09-23 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='from_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fid', to='career_app.login'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='to_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tid', to='career_app.login'),
        ),
    ]
