# Generated by Django 3.2.21 on 2023-09-23 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0002_auto_20230923_1105'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='complaint',
            new_name='complainttable',
        ),
        migrations.RenameModel(
            old_name='feedback',
            new_name='feedbacktable',
        ),
        migrations.RenameModel(
            old_name='notification',
            new_name='notificationtable',
        ),
        migrations.RenameModel(
            old_name='tips',
            new_name='tipstable',
        ),
    ]
