# Generated by Django 3.2.22 on 2023-11-18 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0004_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='JOB',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_app.jobs'),
        ),
    ]
